// CDN asset manifest — real client photography (28 pieces) + final poster artwork.
import piece_01 from "@/assets/piece-01.webp.asset.json";
import piece_02 from "@/assets/piece-02.webp.asset.json";
import piece_03 from "@/assets/piece-03.webp.asset.json";
import piece_04 from "@/assets/piece-04.webp.asset.json";
import piece_06 from "@/assets/piece-06.webp.asset.json";
import piece_07 from "@/assets/piece-07.webp.asset.json";
import piece_08 from "@/assets/piece-08.webp.asset.json";
import piece_09 from "@/assets/piece-09.webp.asset.json";
import piece_10 from "@/assets/piece-10.webp.asset.json";
import piece_11 from "@/assets/piece-11.webp.asset.json";
import piece_12 from "@/assets/piece-12.webp.asset.json";
import piece_13 from "@/assets/piece-13.webp.asset.json";
import piece_14 from "@/assets/piece-14.webp.asset.json";
import piece_15 from "@/assets/piece-15.webp.asset.json";
import piece_16 from "@/assets/piece-16.webp.asset.json";
import piece_17 from "@/assets/piece-17.webp.asset.json";
import piece_18 from "@/assets/piece-18.webp.asset.json";
import piece_19 from "@/assets/piece-19.webp.asset.json";
import piece_20 from "@/assets/piece-20.webp.asset.json";
import piece_21 from "@/assets/piece-21.webp.asset.json";
import piece_22 from "@/assets/piece-22.webp.asset.json";
import piece_23 from "@/assets/piece-23.webp.asset.json";
import piece_24 from "@/assets/piece-24.webp.asset.json";
import piece_25 from "@/assets/piece-25.webp.asset.json";
import piece_26 from "@/assets/piece-26.webp.asset.json";
import piece_27 from "@/assets/piece-27.webp.asset.json";
import piece_28 from "@/assets/piece-28.webp.asset.json";
import poster_1 from "@/assets/poster-1.webp.asset.json";
import poster_2 from "@/assets/poster-2.webp.asset.json";
import poster_3 from "@/assets/poster-3.webp.asset.json";
import logo from "@/assets/logo.webp.asset.json";

export const pieces: string[] = [piece_01.url, piece_02.url, piece_03.url, piece_04.url, piece_06.url, piece_07.url, piece_08.url, piece_09.url, piece_10.url, piece_11.url, piece_12.url, piece_13.url, piece_14.url, piece_15.url, piece_16.url, piece_17.url, piece_18.url, piece_19.url, piece_20.url, piece_21.url, piece_22.url, piece_23.url, piece_24.url, piece_25.url, piece_26.url, piece_27.url, piece_28.url];
export const posters: string[] = [poster_1.url, poster_2.url, poster_3.url];
export const logoUrl = logo.url;
